server:
  port: 8081

spring:
  application:
    name: ms-solicitudes
  r2dbc:
    url: r2dbc:h2:mem:///solicitudesdb?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
  sql:
    init:
      mode: always

logging:
  level:
    com.pragma.crediya.solicitudes: DEBUG
    org.springframework.r2dbc: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
